name: S3 Production Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1 # sets up python in our environment
        with:
          python-version: "3.x" # install python version 3.x, default architecture is x64
      - name: Install AWS CLI
        run: pip3 install awscli --upgrade --user # install the cli with upgrade to any requirements and into the subdir of the user
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1 # use the official GitHub Action from AWS to setup credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Install
        run: |
          npm install
      - name: Production Build
        run: |
          npm run build
      - name: Deploy to S3
        run: aws s3 sync build s3://${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}/site --exclude ".git/*" --exclude ".github/*" --delete # have the bucket have the same content in the repo & exclude the git related directories.
